apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: securemanage
build:
  artifacts:
  - image: securemanage/client
    context: client
    docker:
      dockerfile: Dockerfile
  - image: securemanage/api-gateway
    context: api-gateway
    docker:
      dockerfile: Dockerfile
  - image: securemanage/user-management
    context: UserManagementService
    docker:
      dockerfile: Dockerfile
  - image: securemanage/course-management
    context: CourseManagementService
    docker:
      dockerfile: Dockerfile
  - image: securemanage/payment-management
    context: PaymentManagementService
    docker:
      dockerfile: Dockerfile
  - image: securemanage/enrollment-management
    context: EnrollmentManagementService
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
portForward:
- resourceType: service
  resourceName: client-service
  port: 3000
  localPort: 3000
- resourceType: service
  resourceName: api-gateway-service
  port: 8800
  localPort: 8800
- resourceType: service
  resourceName: mongodb-service
  port: 27017
  localPort: 27017